# === Netlify config for Code by Corey ===
# Security + caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), geolocation=()"

# Long-cache static assets (tweak paths as you add an /assets folder)
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# NOTE: www -> apex redirect is best handled in Netlify Domain settings.
# If you prefer a rule, uncomment below and replace YOUR-NETLIFY-SUBDOMAIN if needed.
# [[redirects]]
#   from = "https://www.codebycorey.dev/*"
#   to = "https://codebycorey.dev/:splat"
#   status = 301
#   force = true
